spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_db
    username: santiago
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: postgresql
      database-platoform: org.hibernate.dialect.PostgreSQLDialect